[build]
builder = "NIXPACKS"
buildCommand = "npm install --no-audit --no-fund && npm run build --workspace=vetpro-web"

[deploy]
startCommand = "npm run start --workspace=vetpro-web"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
